# Swap a 2D array about its principal diagonal

# Required libraries

In [1]:
from math import sqrt

# Taking input

In [2]:
m = input().split(",")
l = list(map(float , m))
print(l)

1,2,3,4,5,6,7,8,9
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


# Calculation

Using function for square matrix

In [3]:
s = int(sqrt(len(l)))
A, O = [], []
for i in range(s):
    a = []
    b = []
    for j in range (s):
        a.append(l[s*i + j])
        b.append(0)
    A.append(a)
    O.append(b)

In [4]:
for i in range(s):
    for j in range(s):
        O[i][j] = A[j][i]

In [5]:
print(O)
for i in O:
    print(i)

[[1.0, 4.0, 7.0], [2.0, 5.0, 8.0], [3.0, 6.0, 9.0]]
[1.0, 4.0, 7.0]
[2.0, 5.0, 8.0]
[3.0, 6.0, 9.0]


Using Transpose function

In [6]:
import numpy as np

In [7]:
A = np.array(l).reshape(s, s)
B = A.transpose()

In [8]:
print(B)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
